### ISSUE TITLE
Cannot resolve 'url' / 'module'

### ISSUE THREAD

**Issue by swissspidy** [buzz/mediainfo.js#113]
### Issue Summary
​

I'm trying to dynamically import `mediainfo.js` in a React hook.

When bundling my app, webpack complains about this code in `dist/mediainfo.js`:

```js
    var _scriptDir = (typeof document === 'undefined' && typeof location
    === 'undefined' ? new (require('u' + 'rl').URL)('file:' + __filename).href
      : typeof document === 'undefined' ? location.href
        : (document.currentScript && document.currentScript.src || new URL(
          'mediainfo.js', document.baseURI).href));
```

```
Module not found: Error: Can't resolve 'url' in '/..node_modules/mediainfo.js/dist'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.
```

When changing that code, it just fails further down the file at the `const { createRequire: createRequire } = await import('module');` and `scriptDirectory = require$1('url').fileURLToPath(new URL('./',` sections.

### Steps to Reproduce

I tried dynamically importing `mediainfo.js` in a React hook like so:

```js
const { default: MediaInfo } = await import(
    /* webpackChunkName: "chunk-mediainfo" */ 'mediainfo.js'
);
```

**Comment by buzz** [comment]
It seems you have problems taming your bundler. Did you see the [React example](https://github.com/buzz/mediainfo.js/tree/gh-pages-src)?

**Comment by swissspidy** [comment]
Ah, looks like one needs to explicitly set `resolve.fallback` like in your React example:

https://github.com/buzz/mediainfo.js/blob/f45714dece22ffc4a93a2cc9d693dca3ddeb463d/webpack.config.js#L105-L110
