### ISSUE TITLE
Add note to install libtool to the Build section of the README

### ISSUE THREAD

**Issue by rmione** [buzz/mediainfo.js#116]
### Suggestion
When building this from Source on Ubuntu 20.04.5 LTS, I ran into some dependency issues, here is a snippet from the npm logs:

```
+ cd ZenLib/Project/GNU/Library/
+ ./autogen.sh
./autogen.sh: 8: libtoolize: not found
./autogen.sh: 18: aclocal: not found
./autogen.sh: 28: automake: not found
Can't exec "aclocal": No such file or directory at /usr/share/autoconf/Autom4te/FileUtils.pm line 326.
autoreconf: failed to run aclocal: No such file or directory
```

I just didn't have `libtool`installed. I figure this may have been left out of the README as it might be assumed? But I think it's worth it to add a note to the Build section of the README to specify this.

### Solution 
Add a note to the Build section of the README to specify that `libtool` needs to be installed. 

I would be glad to make the PR for this if it's felt to be a necessary change. If it's not necessary, no big deal. 

Thanks!

**Comment by buzz** [comment]
You need to have the right build tools available. Refer to the documentation of the projects you try to build, in this case ZenLib.
