### ISSUE TITLE
MediaInfo is to provide basic types of media: Video, Audio, Image, Document, etc

### ISSUE THREAD

**Issue by avmaxim** [buzz/mediainfo.js#117]
### Is your proposal related to a problem?

**MediaInfo** does NOT yeild a type of the media based on its format: `Video`, `Audio`, `Image`, `Document`, etc.

As of now we need to hardcode it and implement our own approach to determine a type of the media based on the array of `tracks` provided in **mediainfo**. But it's not a reliable solution. 

(Write your answer here.)

### Describe the solution you'd like

Ideally we want to have an enum of available types in MediaInfo and a type of the media included in the root of the mediainfo data itself like
```
{
    "@ref": "",
    "@type": "Audio", // a type of the media, for example for ogg, wav, mp3 and other audio formats
    "track": [
        {
            "@type": "General",
            ...
        },
        { ... },
        { ... }
    ]
}
```
(Describe your proposed solution here.)

### Additional context

(Write your answer here.)

### Contribution

(Write your answer here.)

**Comment by avmaxim** [comment]
@buzz Please have a look

**Comment by buzz** [comment]
There's an XSD (XML Schema Definition) available for those types:
https://github.com/MediaArea/MediaAreaXml/blob/master/mediainfo.xsd

A possible route for getting proper typing on those objects might be:

1. (Auto)-convert XSD to [JSON Schema](https://json-schema.org/) or [JSON Type Definition](https://jsontypedef.com/)
2. Use [avj](https://ajv.js.org/guide/typescript.html#type-safe-parsers-and-serializers), a type-safe JSON parser.

I'm not sure if mediainfo.js would be the right place to maintain such a schema. I'd prefer a solution where the schema is either part of official MediaInfoLib or maintained in a separate repository.
