### ISSUE TITLE
Cannot use with Vite

### ISSUE THREAD

**Issue by rstoenescu** [buzz/mediainfo.js#120]
### Issue Summary
​
The file `dist/mediainfo.js` contains `=await import('module')` which breaks the usage with Vite, since what Vite does is a lookup for any import statements.

This was introduced in MediaInfo v0.1.9

### Steps to Reproduce

I will provide a reproduction repo if actually necessary. Apologies for not doing so from the very beginning, but I think that the issue description says it all. If the import statement is transformed to a regular `require()` it will 100% solve the problem.

Please tell me if you still need the reproduction repo or if I should supply any other additional information.

Thank you for your work on this package!

**Comment by NormandoHall** [comment]
Same here #118

**Comment by NormandoHall** [comment]
Good catch @rstoenescu !!! I was downgrade to 0.1.8 and runs perfect with Sveltekit (Vite)

**Comment by buzz** [comment]
Hope this is fixed for you. In any case, there's also an [example on how to setup tooling for Vite](https://github.com/buzz/mediainfo.js/tree/main/examples/vite-react).
