### ISSUE TITLE
Loudness/LUFS Support

### ISSUE THREAD

**Issue by danmkang** [buzz/mediainfo.js#125]
### Is your proposal related to a problem?

Hello! Is there anyway that mediainfo.js could potentially analyze loudness data from an audio file (otherwise known as LUFS)?

I'm looking to have that data on hand for a particular project of mine, but noticed that it's not supported. 

### Describe the solution you'd like

Ideally, the mediainfo.js library would provide a loudness/LUFS parameter for any audio file.

### Additional context

N/A

### Contribution

No

**Comment by JeromeMartinez** [comment]
FYI MediaInfo library, used by mediainfo.js, has no support of decoding so not support of any analyze of content, and it is not planned to have that (it is really a different project if decoders need to be embedded)
