### ISSUE TITLE
Mediainfo.js Can't resolve 'module' in

### ISSUE THREAD

**Issue by mindbugg** [buzz/mediainfo.js#127]
Mediainfo.js is creating issue when using it as a npm

`An error occurred:
Error: Module not found: Error: Can't resolve 'module' in '/node_modules/mediainfo.js/dist'
resolve 'module' in '/node_modules/mediainfo.js/dist'
  Parsed request is a module
  using description file: /node_modules/mediainfo.js/package.json (relative path: ./dist)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /node_modules/mediainfo.js/dist/node_modules doesn't exist or is not a directory
      /node_modules/mediainfo.js/node_modules doesn't exist or is not a directory
      /node_modules/node_modules doesn't exist or is not a directory
      looking for modules in /node_modules
        single file module
          using description file: /package.json (relative path: ./node_modules/module)
            no extension
              /node_modules/module doesn't exist
            .ts
              /node_modules/module.ts doesn't exist
            .tsx
              /node_modules/module.tsx doesn't exist
            .web.js
              /node_modules/module.web.js doesn't exist
            .js
              /node_modules/module.js doesn't exist
            .jsx
              /node_modules/module.jsx doesn't exist
        /node_modules/module doesn't exist
      
`

**Comment by mindbugg** [comment]
nevermind  https://github.com/buzz/mediainfo.js/issues/113 resolved

**Comment by chenweihan** [comment]
I've tried to solve it...It has now been resolved.

这个问题 ./node_modules/mediainfo.js/dist/mediainfo.js:66:20-36 - Error: Module not found: Error: Can't resolve 'module' in 'C:\work\nest-admin-client\node_modules\mediainfo.js\dist'

可以在只需要在 package.json 中配置即可
"browser": {
    "module":false
}
来解决
