### ISSUE TITLE
MaxListenersExceededWarning on multiple analyses run

### ISSUE THREAD

**Issue by danscully** [buzz/mediainfo.js#129]
### Issue Summary
​
I've created an electron app that acts as a droplet for preflight checking media files to certain specifications.  In testing, after 9 or so files, the console shows:
"MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added to [process]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:587:17)
    at process.addListener (node:events:605:10)
    at D:\...\preflight\node_modules\mediainfo.js\dist\mediainfo.js:40:1954"

It reports the same issue for "unhandledRejection" listeners as well.   I'm currently creating an instance for each analysis run and then closing it when done. 

### Steps to Reproduce

I haven't made a reduced reproducible yet, because I'm still evaluating the impact of this issue.  Currently it doesn't seem to effect the results I get, but I'm still early in testing.  Any thoughts?

**Comment by buzz** [comment]
I have setup a test suite where I do around 5000 analyze rounds with ~600 different files on a single `MediaInfo` instance. No issues so far. Maybe there have been updates to Emscripten or Node.js that fixed this already?

Could you provide reproduction?
