### ISSUE TITLE
denpendency not found

### ISSUE THREAD

**Issue by junyo** [buzz/mediainfo.js#131]
using mediainfo.js 0.1.9

running on vue2 + typescript + node14.21.1 

error prints

> ERROR  Failed to compile with 1 errors                                                                         01:40:49
> This dependency was not found:
> 
> * module in ./node_modules/mediainfo.js/dist/mediainfo.js
> 
> To install it, you can run: npm install --save module
> No type errors found
> Version: typescript 4.8.4
> Time: 104083ms

I've checked the path, file is there, but not work

**Comment by NormandoHall** [comment]
Try install as `dependencies`, no `devDependencies`
