### ISSUE TITLE
createRequire is not a function 

### ISSUE THREAD

**Issue by qyjandroid** [buzz/mediainfo.js#137]
React app

code:
import MediaInfoFactory from 'mediainfo.js';

 MediaInfoFactory()
        .then(mediainfo => {
          mediainfo
            .analyzeData(() => file.size, readChunk(file))
            .then(result => {
              console.log('result===', result);
            });
        })
        .catch(e => {
          console.log('meidaFileInfoError==', e);
        });

result: Error
![image](https://github.com/buzz/mediainfo.js/assets/6645414/46f95f6f-984a-4c1d-bcc7-9b34ea4e3017)

**Comment by qyjandroid** [comment]
nodejs  version: 18.15.0

**Comment by buzz** [comment]
Hey @qyjandroid, thanks for filing a bug report. Could you use the [issue template](https://github.com/buzz/mediainfo.js/issues/new?template=BUG_REPORT.md) for bugs and fill in the missing data? Much appreciated
