### ISSUE TITLE
set coverData:true,  but no coverData in result

### ISSUE THREAD

**Issue by qyjandroid** [buzz/mediainfo.js#138]
my code

MediaInfo({ coverData: true }).then((mediainfo: any) => mediainfo
        .analyzeData(() => file.size, this.readChunk(file))
        .then((result: any) => {
           console.log(result);  // I did not found the coverData
         })
there is no coverData in result, where is the coverData?

![image](https://github.com/buzz/mediainfo.js/assets/6645414/1b8148d0-a9c9-46e4-be1b-5faec466180a)

**Comment by buzz** [comment]
Hey @qyjandroid, thanks for filing a bug report. Could you use the [issue template](https://github.com/buzz/mediainfo.js/issues/new?template=BUG_REPORT.md) for bugs and fill in the missing data? Much appreciated
