### ISSUE TITLE
MediaInfoLib 17.10

### ISSUE THREAD

**Issue by diegocr** [buzz/mediainfo.js#14]
Hello,

I did forked this repo and attempted to build a new js file from latest MediaInfoLib 17.10, everything went fine at first glance, but it turns out certain files such as *.mkv returns incomplete metadata (eg, missing Duration, Frame Rate, etc)

By analyzing how these two versions does work (yours, and mine), i can see some strange behavior when invoking `open_buffer_continue` by adding this `console` call at `processChunk`:

```js
...
          seekTo = seekToLow + (seekToHigh * 4294967296);
        }
        console.debug('len=%s, state=%s, offset=%s', l, state, offset, seekToLow, seekToHigh, seekTo)
```

The mkv file i'm using to test has a length of 3914281338 bytes, for reference, the issue is not tied to that specific file.

MediaInfoLib 17.10 gives:
```
len=5242880, state=5, offset=0 -1 -1 -1
len=5242880, state=5, offset=5242880 -1 -1 -1
len=5242880, state=5, offset=10485760 -1 -1 -1
len=5242880, state=5, offset=15728640 -1 -1 -1
len=5242880, state=5, offset=20971520 -1 -1 -1
len=5242880, state=5, offset=26214400 -1 -1 -1
len=5242880, state=7, offset=31457280 -380764220 0 3914203076
len=78262, state=7, offset=3914203076 -1 -1 -1
len=0, state=7, offset=3914281338 -1 -1 -1
```

Your version, latest one on `gh-pages` as of time of this write, gives:
```
len=5242880, state=5, offset=0 -1 -1 -1
len=5242880, state=5, offset=5242880 -1 -1 -1
len=5242880, state=5, offset=10485760 -1 -1 -1
len=5242880, state=5, offset=15728640 -1 -1 -1
len=5242880, state=5, offset=20971520 -1 -1 -1
len=5242880, state=5, offset=26214400 -1 -1 -1
len=5242880, state=5, offset=31457280 -1 -1 -1
len=5242880, state=5, offset=36700160 -1 -1 -1
len=5242880, state=5, offset=41943040 -1 -1 -1
len=5242880, state=5, offset=47185920 -1 -1 -1
len=5242880, state=5, offset=52428800 -1 -1 -1
len=5242880, state=5, offset=57671680 -1 -1 -1
len=5242880, state=5, offset=62914560 -1 -1 -1
len=5242880, state=5, offset=68157440 -1 -1 -1
len=5242880, state=5, offset=73400320 -1 -1 -1
len=5242880, state=7, offset=78643200 -380764220 0 3914203076
len=78262, state=15, offset=3914203076 -1 -1 -1
```

Do you have some clue what the problem could be?

Btw, I did modified `MediaInfo_Inform.cpp` to export to JSON by default when compiling with Emscripten, if you are interested in that i can send you a patch.

**Comment by buzz** [comment]
@diegocr Did you succeed? Might [issue 11](https://github.com/buzz/mediainfo.js/issues/11) be related?

**Comment by diegocr** [comment]
Hi @buzz!

Yes, i did succeed, after compiling the last few versions of MediaInfoLib i was able to track down the issue to some changes introduced in 0.7.94, more specifically on commit https://github.com/MediaArea/MediaInfoLib/commit/82ad4571bd98bb9ac1cf76d6b66cac9aca2ba83a

Reverting that commit does resolves the issue, although it seems the proper way now to finalize the parsing on newer versions is to manually invoke `Open_Buffer_Finalize`, but even so i did reverted back to the former approach.

**Comment by buzz** [comment]
Great to hear!

Did you need to make changes to mediainfo.js in order to build with MediaInfoLib 17.10? I'd be glad to update this project. Grateful for PRs! :)

**Comment by diegocr** [comment]
No, the reason why i did reverted back to the former approach was to prevent having to make changes to mediainfo.js so anytime you would like to upgrade this don't forget to revert that commit, or to integrate the finalize function :)

**Comment by buzz** [comment]
Cool. That's nice to know. Thanks!

**Comment by JeromeMartinez** [comment]
> Reverting that commit does resolves the issue,

Sorry, I saw your bug report but did not yet have the time to handle it.
I don't like the idea to have a patch reverting a bug fix, I'll try to find the reason there is a regression in your case.

> it seems the proper way now to finalize the parsing on newer versions is to manually invoke Open_Buffer_Finalize

It was always the plan to use Open_Buffer_Finalize with this API, it should be used in all cases (before and after the patch).

**Comment by diegocr** [comment]
Hi @JeromeMartinez!

I don't think there is a regression in your code, apparently it's just how mediainfo.js was made to work. That is, it just does expect `Open_Buffer_Continue` to give the Bit3 when it has finished parsing the file, and doesn't handles EOF nor calls the finalize function itself.

On versions prior to 0.9.74 that was fine, since MediaInfoLib was gracefully handling the EOF condition, until the changes introduced in the before mentioned commit, basically.

**Comment by JeromeMartinez** [comment]
@diegocr ha OK, so good that there is no bug, just some small "API break" (we forgot to document this one :( ), and right we don't do anymore gracefully handling the EOF condition as some people work with "growing file" and want to update the file after it reaches EOF (due to new EOF).

@buzz please add `Open_Buffer_Finalize` so it is safe for everyone.
