### ISSUE TITLE
Node: MediaInfoFactory is not a function

### ISSUE THREAD

**Issue by jlw4049** [buzz/mediainfo.js#143]
### Checklist

- [x] I have searched the issue tracker for any duplicate issues and confirmed that this bug has not been reported before.
- [x] I have tested the issue with the upstream project [MediaInfo](https://github.com/MediaArea/MediaInfoLib) and can confirm that the problem only exists in mediainfo.js.
- [x] I have attached all necessary test files, if applicable, so that the issue can be easily reproduced by the developers.
- [x] I have added a reproduction repository or a code sandbox that clearly illustrates the issue. Providing a minimal example will greatly help the developers in understanding and resolving the problem.

### Bug Description

I've been trying to use mediainfo.js via Node (the library (and the cli on Windows doesn't work at all)). When I try to use it via the library method https://github.com/buzz/mediainfo.js/blob/main/API.md I get `MediaInfoFactory is not a function.` I'm fairly new to Node so I spent the last 6 hours trying different combinations to try to solve it but with no success.

### Steps to Reproduce

Install latest Node (LTS)
Run npm install mediainfo.js
Create a script to try to use MediaInfoFactory()
Run script via `node scriptname.js`

### Expected Behavior

To parse a mediafile
### Actual Behavior

MediaInfoFactory is not a function
### Environment

- latest mediainfo.js
- tested in linux/windows 11
- latest version of chrome
- tried with electron as well

### Additional Information

**Example code:** (I tried code from the **CLI** and issues I found that was closed here on the tracker, neither worked)
```js
const MediaInfoFactory = require('mediainfo.js');

const createMediaInfo = async () => {
  // Create a new MediaInfo instance
  const mediainfo = await MediaInfoFactory();
  return mediainfo;
};

const extractMediaInfo = async (fileBuffer) => {
  try {
    // Create a MediaInfo instance
    const mediainfo = await createMediaInfo();

    // Analyze the media data
    const result = await mediainfo.analyzeData(
      () => fileBuffer.length,
      (size, offset) => Promise.resolve(fileBuffer.slice(offset, offset + size))
    );

    // Close the MediaInfo instance
    mediainfo.close();

    return result;
  } catch (error) {
    throw new Error(`Error analyzing media: ${error.message}`);
  }
};

// Usage example:
const fs = require('fs');

// Load the media file into a buffer (you can replace 'media.mp4' with your file path)
const fileBuffer = fs.readFileSync("C:/Users/jlw_4/OneDrive/Desktop/testing/audio test.mkv");

// Extract media information
extractMediaInfo(fileBuffer)
  .then((result) => {
    console.log(result);
  })
  .catch((error) => {
    console.error(error);
  });

```
I could very well be doing something wrong, if so I apologize for opening this up as a bug.

**Comment by buzz** [comment]
If you replace the first line, it will magically work:

```
const { default: MediaInfoFactory } = require("mediainfo.js");
```

This is necessary when you use it with a CommonJS module system because mediainfo.js is an ESM package. It boils down to JavaScript having multiple partially incompatible module systems. There are tons of blog posts about this topic. Just search the internet.

**Comment by jlw4049** [comment]
I appreciate the quick response and I can confirm this works fine. I'm very experience in python/python web frameworks but node is another beast I'm learning. Thanks man!
