### ISSUE TITLE
Base64 decoding error

### ISSUE THREAD

**Issue by FastGUI** [buzz/mediainfo.js#151]
![image](https://github.com/buzz/mediainfo.js/assets/35055114/23a9e9c1-08c3-47b6-97b3-08cf4fbc6607)
![image](https://github.com/buzz/mediainfo.js/assets/35055114/bdc123bf-34a9-40b2-a4f2-c482f95cf302)

Google Chrome  121.0.6167.161

**Comment by buzz** [comment]
Hey, thanks for opening an issue. Could you please use [this issue template](https://github.com/buzz/mediainfo.js/blob/main/.github/ISSUE_TEMPLATE/BUG_REPORT.md) for filing bugs? Thank you!
