### ISSUE TITLE
autogen.sh not found does not exist when building the mac system

### ISSUE THREAD

**Issue by jett6680** [buzz/mediainfo.js#153]
### Checklist

- [ ] I have searched the issue tracker for any duplicate issues and confirmed that this bug has not been reported before.
- [ ] I have tested the issue with the upstream project [MediaInfo](https://github.com/MediaArea/MediaInfoLib) and can confirm that the problem only exists in mediainfo.js.
- [ ] I have attached all necessary test files, if applicable, so that the issue can be easily reproduced by the developers.
- [ ] I have added a reproduction repository or a code sandbox that clearly illustrates the issue. Providing a minimal example will greatly help the developers in understanding and resolving the problem.

### Steps to Reproduce

1.pnpm install
2. pnpm build
3. ...

### Expected Behavior

should build success

### Actual Behavior

autogen.sh not found does not exist so build fali

### Environment

- mediainfo.js version: [e.g. 1.2.3]
- Operating System: [e.g. Windows 10, macOS Big Sur]
- Browser (if applicable): [e.g. Chrome 90, Firefox 87]
- Node.js (if applicable): [e.g. 18.16.0]

**Comment by buzz** [comment]
Please fill out the bug report. Include all relevant information including console logs. Thank you

**Comment by jett6680** [comment]
> Please fill out the bug report. Include all relevant information including console logs. Thank you

gulp/compile/mediainfolib.ts 
9 line ==> await spawn('./autogen.sh', [], mediainfolibDir)

the file './autogen.sh' does not exist.
