### ISSUE TITLE
Live Demo no longer works as of 2024-06-01

### ISSUE THREAD

**Issue by RodrigoTR04** [buzz/mediainfo.js#156]
### Checklist

- [x] I have searched the issue tracker for any duplicate issues and confirmed that this bug has not been reported before.
- [x] I have tested the issue with the upstream project [MediaInfo](https://github.com/MediaArea/MediaInfoLib) and can confirm that the problem only exists in mediainfo.js.
- [x] I have attached all necessary test files, if applicable, so that the issue can be easily reproduced by the developers.
- [Don't know what this means] I have added a reproduction repository or a code sandbox that clearly illustrates the issue. Providing a minimal example will greatly help the developers in understanding and resolving the problem.

### Steps to Reproduce

1. Load up the live demo: https://mediainfo.js.org/demo/
2. Drag and drop/click and select video file
3. Media information will not be displayed
4. (See attached image at the end of the issue)

### Expected Behavior

Expected behavior is that it would display media information.

### Actual Behavior
Visibly nothing happens

### Environment

- Operating System: Windows 10 Pro
- Browser: Firefox 126.0.1

### Additional Information

![image](https://github.com/buzz/mediainfo.js/assets/65554156/95142626-8e6f-4c37-8d0c-8bedbefe6ea7)

**Comment by buzz** [comment]
Hey, thanks for reporting. The fix is in 4c1f4fc4f9dc1ca490b7392db6d214428431f819. If it still doesn't work, please make sure to clear your browser cache.

**Comment by RodrigoTR04** [comment]
> Hey, thanks for reporting. The fix is in [4c1f4fc](https://github.com/buzz/mediainfo.js/commit/4c1f4fc4f9dc1ca490b7392db6d214428431f819). If it still doesn't work, please make sure to clear your browser cache.

Yes it's working as intended now, as a side feature request would it be possible to have a more compact theme option? Some files with multiple audio tracks for different languages get very long and scrolling up and down all the time can take quite some time and doesn't fit nicely inside a screenshot.

**Comment by buzz** [comment]
> Yes it's working as intended now, as a side feature request would it be possible to have a more compact theme option?

I agree, when working with files that have many tracks, the display is not so great.

I'm not sure if this serves your use case (taking screenshots), but I made the theme more compact. Also, I made the tracks collapsible. (78771d904aeb91040cf8403a192ef3b2a66157ab)

**Comment by RodrigoTR04** [comment]
> I'm not sure if this serves your use case (taking screenshots), but I made the theme more compact. Also, I made the tracks collapsible. ([78771d9](https://github.com/buzz/mediainfo.js/commit/78771d904aeb91040cf8403a192ef3b2a66157ab))

It's great right now, much easier to take a screenshot and also much easier to focus on a certain video or audio track without having to scroll down all the time. Thanks for the change!
