### ISSUE TITLE
Can't lauch with React. Error - export 'MediaInfo' was not found in 'mediainfo.js'

### ISSUE THREAD

**Issue by StasSpawn** [buzz/mediainfo.js#160]
1) npx create-react-app my-app
2) npm install mediainfo.js 
3) Add app.js from https://github.com/buzz/mediainfo.js/blob/main/examples/webpack-react/src/App.tsx
4) Remove TS things (using simple js) 

And **export 'MediaInfo' (imported as 'MediaInfo') was not found in 'mediainfo.js' (possible exports: default, isTrackType, mediaInfoFactory)** error appeared. 

![2024-09-20_160711](https://github.com/user-attachments/assets/637fcb6b-8e0e-4559-af89-4cc6e336d021)

**Comment by StasSpawn** [comment]
Fix this error by removing MediaInfo from **useRef(MediaInfo)**

But now new errors after adding video to input
![2024-09-20_163626](https://github.com/user-attachments/assets/125010ab-579b-4efd-9cc9-103bfa337c1c)

**Comment by buzz** [comment]
- If you want to report a bug, please use the [issue template](https://github.com/buzz/mediainfo.js/blob/main/.github/ISSUE_TEMPLATE/BUG_REPORT.md?plain=1).
- If you want to ask a programming question, please do so on [SO](https://stackoverflow.com/search?q=mediainfo.js).

Thank you :pray:
