### ISSUE TITLE
Using mediainfo.js with Angular

### ISSUE THREAD

**Issue by Laazarus** [buzz/mediainfo.js#20]
Hello,

I am trying to use this library in my application written in Angular 7. 

I could not compile the project as explained because it appears it can be compiled only on a 32 bit machine and on my machine is giving a lot of problems, so I am using the mediainfo.js and mediainfo.js.mem that I found in the repository.

After many attempts, I can load mediainfo.js but I get always the error that infomedia.js.mem cannot be found.

I tried all the possible combinations modifying the path in mediainfo.js but it looks like there is no way to get it loaded.

I checked the source of the demo on the internet but  I could not see loaded on the there too.

Does anyone else use this library with Angular? Or any other library such as React to Vue?

Thanks for this library and for the help.

Regards

Nic

**Comment by buzz** [comment]
Did you look at the example on how to use it?
https://github.com/buzz/mediainfo.js/blob/gh-pages/js/mediainfopage.js

> I could not compile the project as explained because it appears it can be compiled only on a 32 bit 

That's not correct. I actually never tried to compile it on a 32 bit machine.

> After many attempts, I can load mediainfo.js but I get always the error that infomedia.js.mem cannot be found.

There's `memoryInitializerPrefixURL` which can be used to customize the load path for `infomedia.js.mem`. As you can see, it defaults to `./`.

> Does anyone else use this library with Angular? Or any other library such as React to Vue?

You should be able to use mediainfo.js with Angular. Just follow a guide on how to integrate third-party libraries.

**Comment by Laazarus** [comment]
Hello,
So o was able to integrate (partially so far) the library. It result to be a bit of a pain in angular but it is doable. Still I cannot compile the library on Ubuntu, keeps shooting errors so I m using the files found in the demo.

The path for the mem file was tricky but that is due to how angular works.

Still not able to make it work 100% but getting there. Happy to share the findings if anyone interested.

On 18 Aug 2019 10:51, buzz <notifications@github.com> wrote:

Did you look at the example on how to use it?
https://github.com/buzz/mediainfo.js/blob/gh-pages/js/mediainfopage.js

I could not compile the project as explained because it appears it can be compiled only on a 32 bit

That's not correct. I actually never tried to compile it on a 32 bit machine.

After many attempts, I can load mediainfo.js but I get always the error that infomedia.js.mem cannot be found.

There's memoryInitializerPrefixURL which can be used to customize the load path for infomedia.js.mem. As you can see, it defaults to ./.

Does anyone else use this library with Angular? Or any other library such as React to Vue?

You should be able to use mediainfo.js with Angular. Just follow a guide on how to integrate third-party libraries.

**Comment by Laazarus** [comment]
And Sorry the problem is not on 64 bit but when is compiling on 32 apparently there are some checks to understand if size_t is a long and sometimes gives problems. Maybe my configuration is particularly unlucky

On 18 Aug 2019 10:51, buzz <notifications@github.com> wrote:

Did you look at the example on how to use it?
https://github.com/buzz/mediainfo.js/blob/gh-pages/js/mediainfopage.js

I could not compile the project as explained because it appears it can be compiled only on a 32 bit

That's not correct. I actually never tried to compile it on a 32 bit machine.

After many attempts, I can load mediainfo.js but I get always the error that infomedia.js.mem cannot be found.

There's memoryInitializerPrefixURL which can be used to customize the load path for infomedia.js.mem. As you can see, it defaults to ./.

Does anyone else use this library with Angular? Or any other library such as React to Vue?

You should be able to use mediainfo.js with Angular. Just follow a guide on how to integrate third-party libraries.
