### ISSUE TITLE
[Question] - Get raw output value

### ISSUE THREAD

**Issue by at-cuongtran** [buzz/mediainfo.js#21]
Hello there,

Thank you for an awesome library, everything is working fine so far, and I got a question about the output value. Currently, all the values are parsed to the human-friendly format. For example, the `Duration` is `1h 13mn`.  I wonder if I can get the raw value without any format, just the number so I can format it to the way I like.

In the demo website of [Mediainfo Demo](https://mediaarea.net/MediaInfoOnline), you can get the raw values with `XML` or `JSON` output option, but not others.

**Comment by buzz** [comment]
mediainfo.js is just a JavaScript port of https://mediaarea.net/en/MediaInfo.

Please refer to the [MediaInfo API](https://mediaarea.net/en/MediaInfo/Support/SDK).
