### ISSUE TITLE
Using the library from the file-protocol possible?

### ISSUE THREAD

**Issue by tiptronic** [buzz/mediainfo.js#27]
This library is awesome and works pretty good!

Here's one thing, though (I don't know, if this can get solved using wasm at all):

Since mediainfo uses `fetch` to load data, I'm unable to run it from the `file://` protocol.
I tried to polyfill `fetch, but get this error:

> wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': An argument must be provided, which must be a Response or Promise<Response> object

Any hint, if it is even possible to use mediainfo.js from the `file://`protocol?

**Comment by buzz** [comment]
According to https://emscripten.org/docs/compiling/Deploying-Pages.html it seems the `file://` protocol is not supported.

What exactly is your use case/environment? You can always spin up a small webserver to have the files served via http.

**Comment by tiptronic** [comment]
Thx for the hint!

Unfortunately I can't spin up a small webserver, because the code runs inside a plugin (which in turn is loaded/run via the `file://` - protocol).

I was under the impression, that Emscripten supports the `file://` protocol:

https://emscripten.org/docs/compiling/Running-html-files-with-emrun.html

I'm new to Emscripten, so atm. I have no clues, but I think this is interesting enough to play with it... 

Btw: All my stuff tends to run using the `file://` protocol (this is also how you distributed your manuals/docs 20 years ago - so it's kinda stupid that everybody seems to require a `small webserver` on my machine (which would neither run on an iPad, nor for my grand-ma (if you know what I mean ;) )

**Comment by buzz** [comment]
> Unfortunately I can't spin up a small webserver, because the code runs inside a plugin

What kind of plugin? What application is the plugin for? Are you in a browser or node environment? etc.

Please provide some useful information or it's difficult to help.

> I was under the impression, that Emscripten supports the file:// protocol:
> https://emscripten.org/docs/compiling/Running-html-files-with-emrun.html

You are linking the documentation for emrun. That's a *small webserver* you can use to serve emscripten stuff, so you don't have to use `file://`. They also explain why `file://` is problematic: CORS

**Comment by tiptronic** [comment]
I know all those artificial restrictions. In Chromium you can switch those off using various settings.

Anyway - the target is a Qt application (where I don't have access to the embedded Chromium flags), which runs a QTWebEngine-webview from the `file://` protocol. That's approx. the same as if you run (double-click) a local .html file using Chrome.  (For my current project there's an additional restriction that I can not use timer-apis (e.g. `requestAnimationFrame`, `setTimeout`, etc...) - but that's something else...)

Please don't bother with it... - your comments already helped me! 
I will dig into it once I find some time and keep you posted in case I find something useful -> it's not that important and the use-case is pretty special.

PS: Otoh the library could come in very handy for my own (private) projects, where I want it to run on the `file://` protocol too.

**Comment by JeromeMartinez** [comment]
> In Chromium you can switch those off using various settings.

If I remember correctly our [MediaInfo Javascript version](https://mediaarea.net/en/MediaInfo/Download/JavaScript) was working well with local files on Firefox before they change to CORS, so it should work if you can deactivate this security feature in your Qt app.

**Comment by g-maxime** [comment]
I don't know if it's possible with QtWebEngine API. But this example for Android intercepts requests and loads files locally :
https://github.com/MediaArea/MediaInfoLib/blob/master/Project/Android/MediaInfoJs/app/src/main/java/com/example/mediainfojs/MainActivity.kt

**Comment by tiptronic** [comment]
Thx @JeromeMartinez 
If I load your files (`HowToUse_Dll.html`) I also get this error 

> failed to asynchronously prepare wasm: failed to load wasm binary file at 'MediaInfoWasm.wasm'...

in Chrome, Safari, etc... **but it works** in Firefox Developer Edition.

So your hint to try Firefox was great!

Maybe just overwriting (or intercepting) the Fetch API will make it work already. Thx @g-maxime for the link...

(Now I just need to find some time... maybe weekend)

Anyway - thanks a lot; it's good to see, there are others out there who care about the file-system ;)

**Comment by tiptronic** [comment]
Overwriting fetch seems not to be enough, but now we're getting closer in Chrome as well:

> mediainfo.min.js:1 
wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': An argument must be provided, which must be a Response or Promise\<Response\> object

**Comment by tiptronic** [comment]
@buzz @JeromeMartinez 

Just for completeness sake:
Overwriting `fetch` with a promisified `XMLHttpRequest` does the job pretty good. For me it work on all required browsers.
Here's the quick code (it just emulates fetch's request returning a promised 'arraybuffer' ):

```
window.fetch = ( ...inParm ) => {
    const path = inParm[ 0 ];
    return new Promise( function( resolve, reject ) {
        const req = new XMLHttpRequest();
        req.withCredentials = true; // should be default anyway
        req.responseType = 'arraybuffer';

        req.addEventListener( 'load', () => {
            resolve( {
                ok: true,
                arrayBuffer: () => Promise.resolve( req.response )
            } );
        } );

        [ 'abort', 'error' ].forEach( ( evt ) => { req.addEventListener( evt, ( error ) => { reject( error ) } ) } );
        req.open( 'GET', path );
        req.send();
    } )
}

```

Thanks again for your kind help!

**Comment by buzz** [comment]
Closing issue as it seems to be resolved.
