### ISSUE TITLE
could not load "mediainfo.wasm" in electron renderer

### ISSUE THREAD

**Issue by heyask** [buzz/mediainfo.js#28]
```
GET //mediainfo.wasm net::ERR_FILE_NOT_FOUND
index.html:1 Uncaught (in promise) TypeError: Failed to fetch
```

```
mediainfo.js:874 GET http://mediainfo.wasm/ net::ERR_NAME_NOT_RESOLVED
Uncaught (in promise) TypeError: Failed to fetch
```

I'm using electron and react.
and import mediainfo.js from App.js with this line. ```import MediaInfo from "mediainfo.js";```
I put mediainfo.wasm file into /public directory, but not works.

**Comment by buzz** [comment]
It depends on how electron JS bundling works which I don't know much about. But in general you need to make sure `mediainfo.wasm` is copied to the same location as `mediainfo.js`.

Could you share a test repository?

Also: In case electron is using the `file://` handler this is related: #27

**Comment by heyask** [comment]
@buzz sorry for late reply. 

[test repository](https://github.com/heyask/electron-cra-boilerplate/blob/master/src/App.js) I made.

type following in terminal.
```
npm run start 
npm run electron
```

and you can see the error.
```
Uncaught (in promise) RuntimeError: abort(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0). Build with -s ASSERTIONS=1 for more info.
    at abort (http://localhost:3000/static/js/0.chunk.js:3128:17)
    at http://localhost:3000/static/js/0.chunk.js:3222:15
```

usually, ```magic word 00 61 73 6d, found 3c 21 44 4f``` error is .wasm file not found.

I looked into node_modules/mediainfo.js, but there was already mediainfo.wasm.

![스크린샷 2020-04-20 오후 1 24 05](https://user-images.githubusercontent.com/13181635/79713954-4cd28c80-830a-11ea-808b-71a0a5edee08.png)

**Comment by buzz** [comment]
Thanks for sharing the test repository.

The issue is not related to electron. Your webpack build doesn't include `mediainfo.wasm`. If you investigate using the browsers developer tools, you can see that the request for `mediainfo.wasm` is 200 success, but your app returns some HTML page, not the wasm file. Thus you're getting the magic word error.

https://mediainfo.js.org/ is a React app bundled with webpack. You can use it as a reference. I also [published the code](https://github.com/buzz/mediainfo.js/tree/gh-pages-src) for it. To solve the problem I chose to customize the [webpack configuration](https://github.com/buzz/mediainfo.js/blob/gh-pages-src/webpack.config.js#L32) so that `mediainfo.wasm` is copied over to the destination folder (using the `copy-webpack-plugin`).

**Comment by heyask** [comment]
@buzz thank you for your help. I uploaded wrong test repo.

I pushed new update in [test repo with electron with below changes](https://github.com/heyask/electron-cra-boilerplate/blob/f56a95755643f0e7bdb70797f83db7ba5a4e2d6b/config-overrides.js#L11)

I added [webpack target](https://github.com/heyask/electron-cra-boilerplate/blob/f56a95755643f0e7bdb70797f83db7ba5a4e2d6b/config-overrides.js#L11) to "electron-renderer"

and in electron.js, added option to [nodeIntegration: true](https://github.com/heyask/electron-cra-boilerplate/blob/f56a95755643f0e7bdb70797f83db7ba5a4e2d6b/public/electron.js#L11) 
because using ipcRenderer outside of electron(like react) requires that options. or it will show errors like these ```fs.existsSync is not a function``` or ```"events":1 Uncaught ReferenceError: require is not defined```

type ```npm run electron-dev``` and you can see 
```Failed to load resource: net::ERR_NAME_NOT_RESOLVED -------- http://mediainfo.wasm/```

I checked out ```node_modules/mediainfo.js/dist/mediainfo.js``` file on line 82 with ```locateFile``` function

in that function, scriptDirectory returns ```//```.
```return scriptDirectory + path``` is replaced with ```//mediainfo.wasm```
so I editted ```scriptDirectory``` to "./".
and then, It works.

can you check that part of code?

**Comment by tumidi** [comment]
The `locateFile` function is part of the emscripten loader code. I think they tailored it towards being used inside a real browser context. It might be that you need to patch the code in order to make electron find the `mediainfo.wasm`.

**Comment by heyask** [comment]
@tumidi  ah ok. I'll check it out more.

**Comment by buzz** [comment]
The `locateFile` function is part of the emscripten loader code. I think they tailored it towards being used inside a real browser context. It might be that you need to patch the code in order to make electron find the `mediainfo.wasm`.
