### ISSUE TITLE
Npm Module

### ISSUE THREAD

**Issue by amilajack** [buzz/mediainfo.js#3]
The ability to use this as an npm module would be a nice addition.

**Comment by buzz** [comment]
This is meant to be run in the browser. So npm module is somewhat unimportant I guess.
For node you might want to use MediaInfo natively through one of the available bindings?

**Comment by amilajack** [comment]
I opened the issue because I wanted to use it with electron. I use a module loader to compile all my scripts so it would be nice if I didn't have to use a script tag or what not.

**Comment by buzz** [comment]
`pre.js` and `post.js` already have some wrapping code and look like the place you're looking for?

Bother to create a proper PR? :)

**Comment by amilajack** [comment]
Sure thing! But I dont think I will be able to compile the source. Is there a way that you can compile the source for me?

**Comment by buzz** [comment]
Come on, just check the readme. It's not hard: https://github.com/buzz/mediainfo.js#build
You would have to do build anyways to properly test everything.

**Comment by amilajack** [comment]
Sorry. I should have clarified my situation. LLVM is broken on my machine.

**Comment by buzz** [comment]
Ok. No problem.

**Comment by amilajack** [comment]
I was also wondering if you could offer an overview of the API of the module.

**Comment by buzz** [comment]
https://github.com/buzz/mediainfo.js#using-mediainfojs
