### ISSUE TITLE
Reduce WASM file-size

### ISSUE THREAD

**Issue by realies** [buzz/mediainfo.js#30]
Any ideas on how to optimise the file size of the web assembly? Using `wasm-opt` with the `-Oz` parameter managed to bring down the WASM from `4.6M` to `4.3M`. Wonder if stripping symbols or _somehow_ shaking the tree from the rest of the libraries could help reduce file size further.

**Comment by buzz** [comment]
Optimization is currently set to `-O0`.

I don't get it smaller than 4.3M though:

```
4648131 dist-O0/mediainfo-opt.wasm
5077298 dist-O0/mediainfo.wasm
4545539 dist-O2/mediainfo-opt.wasm
4590547 dist-O2/mediainfo.wasm
4432004 dist-Os/mediainfo-opt.wasm
4457593 dist-Os/mediainfo.wasm
4432781 dist-Oz/mediainfo-opt.wasm
4445860 dist-Oz/mediainfo.wasm
```

Compiler flag set in `build.sh`: `OPTS="-Ox"`. `*-opt.wasm` files were additionally post-processed with `wasm-opt -Oz`.

Also, optimizing for size means lower runtime speed. So tests should be made I guess. For the time being I would propose using `-O2`?

I assume there's potential of reducing wasm size further. But more research and testing should be made for which I currently lack the time. This has good information on the topic (for Rust but most still applies):  
https://rustwasm.github.io/book/reference/code-size.html

**Comment by videoinu** [comment]
Interestingly mediainfo have their own online service at https://mediaarea.net/MediaInfoOnline and the wasm bundle is less than three megabytes

**Comment by JeromeMartinez** [comment]
> Interestingly mediainfo have their own online service at https://mediaarea.net/MediaInfoOnline and the wasm bundle is less than three megabytes

[we disable a couple of features we don't need for MediaInfoOnline](https://github.com/MediaArea/MediaInfoLib/blob/master/Project/GNU/Library/AddThisToRoot_DLL_compile.sh#L57-L62), and we plan to reorganize the source code for lowering even more the size (but currently not a priority as our sponsors don't care much about the size of the WASM version).

**Comment by buzz** [comment]
That's interesting. Are the flags and their specific consequences documented somewhere?

And then, what features MediaInfo is loosing, e. g. analyzing particular files/codecs?

**Comment by JeromeMartinez** [comment]
@buzz no doc, in summary no [MediaTrace](https://mediaarea.net/MediaTrace) (the most impacting for size IIRC), no advanced options (optional checking validity of FFV1 or MPEG Video...), no directory/file support (JS uses the "by buffer" API so fine). No loss in analyzing particular files/codecs for 99.999% of online users.

**Comment by buzz** [comment]
Sounds great. I will incorporate these flags then.
Thanks for the hint! @JeromeMartinez
