### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by nikitatrifan** [buzz/mediainfo.js#32]
Hey there!

It seems like there is a bug. Here is what I'm getting when playing around with the library using create react app template:

```
Uncaught (in promise) RuntimeError: abort(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0). Build with -s ASSERTIONS=1 for more info.
    at abort (http://localhost:3000/static/js/1.chunk.js:3145:17)
    at http://localhost:3000/static/js/1.chunk.js:3239:15
```

That's how the lib is being imported:
```
import MediaInfo from 'mediainfo.js'
```

Any suggestions? Thanks!

**Comment by nikitatrifan** [comment]
Just tested the minified version being loaded from unpkg and looks like it works properly. But compiling fails when I import it from node_modules.

**Comment by novolog** [comment]
I have the same issue, working on it, it seems that `3c 21 44 4f` is actually `<!DO` in ASCII. So it tries to load an actual HTML as wasm.

**Comment by buzz** [comment]
The WASM loader tries to load `mediainfo.wasm`. It determines the URL relative to `mediainfo.js`.
When using a CDN this just works because `mediainfo.wasm` is published in the `dist` folder.

When you're using a custom bundler build flow you need to make sure to copy `mediainfo.wasm` to your output directory. Check the [source code](https://github.com/buzz/mediainfo.js/blob/gh-pages-src/webpack.config.js#L34) of https://mediainfo.js.org/ on how this is achieved using webpack and `copy-webpack-plugin`.

Docs on using a JS bundler could be improved, I guess.

**Comment by dcfranca** [comment]
Is it possible to load the wasm on a create-react-app project without needing to eject it?

**Comment by buzz** [comment]
> Is it possible to load the wasm on a create-react-app project without needing to eject it?

As long as create-react-app is able to serve the WASM file via HTTP you're good to go. Usually it's sufficient to drop the file in a `public` folder or similar.

**Comment by dcfranca** [comment]
@buzz thanks for the quick reply

Just to clarify that I'm running on development mode

I've tried a few things:
I do have a public folder, so I copied the `MediaInfoModule.wasm` there, didn't work

I, then, copied both `mediainfo.js` and `MediaInfoModule.wasm` under my `src` folder, I understood that both need to be on the same folder... and changed the import to:
`import MediaInfo from '<my_folder>/mediainfo.js';`

Also didn't work

I feel that I'm missing something very silly here

The error message:
```
Uncaught RuntimeError: abort(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0). Build with -s ASSERTIONS=1 for more info.
abort @ <myDir>/src/static/mediainfo.js:42
```

**Comment by dcfranca** [comment]
I made it work loading from the CDN! thanks

**Comment by wpchen** [comment]
@dcfranca, can you describe what you did? I am in a similar situation where I'm trying to get it to work in React (via create-react-app). The demo React+webpack doesn't quite apply as create-react-app abstracts away the webpack.config.json. I tried the same things you did -- copied .wasm file to my public folder (and it's being served with 200 status per Dev Console).
