### ISSUE TITLE
binding error

### ISSUE THREAD

**Issue by PlexPt** [buzz/mediainfo.js#34]
![image](https://user-images.githubusercontent.com/15922823/84614727-99e17200-aef9-11ea-971a-8b68867a431a.png)

I use npm install this lib
and code is 

![image](https://user-images.githubusercontent.com/15922823/84614799-cc8b6a80-aef9-11ea-9de9-5e3d6f23c9ff.png)

![image](https://user-images.githubusercontent.com/15922823/84614780-c1d0d580-aef9-11ea-93a1-4aca5273a9ed.png)

**Comment by buzz** [comment]
I need more information to help you.
Could you provide a minimal repository?

**Comment by PlexPt** [comment]
@buzz https://github.com/PlexPt/KiwiBox

**Comment by PlexPt** [comment]
src/renderer/pages/PTGen/PTGen.vue

**Comment by buzz** [comment]
I created a minimal example using Vue.js and Element on CodePen:
https://codepen.io/buzzone/pen/PoZGaYy

It works just fine.
