### ISSUE TITLE
cover data / advanced build

### ISSUE THREAD

**Issue by czaux** [buzz/mediainfo.js#35]
in the build.sh file the advanced options appear to be turned off with `-DMEDIAINFO_ADVANCED_NO` which appears to stop
cover data according to this mediainfo commit: https://github.com/MediaArea/MediaInfoLib/commit/d8fd88a1c282d1c09388c55ee0b46029e7330690

I'm not sure if there's other changes that have to be done to pass the cover_data option properly, but the gist below is what I've tried.

https://gist.github.com/czaux/3af94d8f867b730be2fd265b0c0380c1#file-mediainfo-js-L12

**Comment by buzz** [comment]
You cannot pass `cover_data` as it is not an allowed option for `MediaInfo`.

If you need cover data to be returned I can see two options:

1. Try building mediainfo.js with `-DMEDIAINFO_ADVANCED_NO` off. (WASM module file size would probably increase.)
2. Patch MediaInfoLib yourself by enabling [this](https://github.com/MediaArea/MediaInfoLib/blob/d8fd88a1c282d1c09388c55ee0b46029e7330690/Source/MediaInfo/Audio/File_Flac.cpp#L273) manually.

**Comment by JeromeMartinez** [comment]
>  (WASM module file size would probably increase.)

@buzz this is my personal choice to drop such option in my own deliveries, but maybe your user are more interested in such kind of options, you may be interested in disabling this compilation flag, the WASM module file size will increase but not so much so maybe acceptable by you.

**Comment by buzz** [comment]
@czaux Option `coverData` is published on NPM.
