### ISSUE TITLE
some info like DURATION not detected in mpg format

### ISSUE THREAD

**Issue by sajadghobadi** [buzz/mediainfo.js#36]
thank for your great library.
i use web js version of library but DURATION not loaded for mpg file.
in other format like mkv,avi , ... duration load nicely but this problem occur only in mpg format

**Comment by buzz** [comment]
What mpg file are you using?

Can you try this file for testing? https://filesamples.com/samples/video/mpg/sample_640x360.mpg

You can also try your mpg file in the [standalone MediaInfo application](https://mediaarea.net/de/MediaInfo/Download).

**Comment by sajadghobadi** [comment]
thanks for your answer,
duration in your mpg file worked correctly but my mpg video dose not work.
i try to cut some seconds of my mpg video. it is interested that duration of output video from cut worked!!!
my video size is large but i attach mediainfo text file my be usefull  to helping me.
[72_372_1_1_E'laanMonaazereyeDaaneshjooyi__Pre_1.mpg.txt](https://github.com/buzz/mediainfo.js/files/4947992/72_372_1_1_E.laanMonaazereyeDaaneshjooyi__Pre_1.mpg.txt)

**Comment by sajadghobadi** [comment]
i found  file with min size for looking at.
please test it :
https://gofile.io/d/rHixvr

**Comment by buzz** [comment]
I can confirm mediainfo.js doesn't show particular fields in the output for the `06.mpg` test file. Here I'm comparing the text output of mediainfo.js and MediaInfo CLI. The following fields are missing from mediainfo.js output:

```
General
Duration                                 : 10 s 920 ms
Overall bit rate                         : 16.5 Mb/s

Video
Duration                                 : 10 s 920 ms
Bit rate                                 : 15.8 Mb/s
Bits/(Pixel*Frame)                       : 0.305
Stream size                              : 20.6 MiB (96%)

Audio
Duration                                 : 10 s 920 ms
Frame rate                               : 41.667 FPS (1152 SPF)
Stream size                              : 512 KiB (2%)
```

I did some tests on other files and can find that other MPEG-1/2 files are also affected. It seems though only CBR isn't recognized correctly. VBR seems to work fine.

**CBR files (missing fields)**
http://hubblesource.stsci.edu/sources/video/clips/details/images/centaur_1.mpg (MPEG-1)
http://hubblesource.stsci.edu/sources/video/clips/details/images/centaur_2.mpg (MPEG-2)

**VBR files (working)**
https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mpg-file.mpg
https://www.fileformat.info/format/mpeg/sample/567fd6a0e0da4a8e81bdeb870de3b19c/download

**Comment by buzz** [comment]
@JeromeMartinez:

I did some more testing. Interestingly the provided test file `06.mpg` runs just fine in MediaInfo CLI/Desktop and on MediaInfoOnline while in my WASM build it is missing the mentioned fields.

But `centaur_1.mpg` doesn't work properly on MediaInfoOnline: https://mediaarea.net/MediaBin/AfEUougy
It does work with MediaInfo CLI/Desktop though.

**Comment by sajadghobadi** [comment]
@buzz  thanks for your response and interest info.
but i use of mediainfo library in beowser. like https://mediainfo.js.org/ so i can't use cli/desktop mediainfo.
do you have any idea for web ?

**Comment by buzz** [comment]
> @buzz thanks for your response and interest info.
> but i use of mediainfo library in beowser. like https://mediainfo.js.org/ so i can't use cli/desktop mediainfo.
> do you have any idea for web ?

Yes, I understand. The browser/WASM builds do currently have this issue and it is yet unresolved.

**Comment by JeromeMartinez** [comment]
@buzz
For `centaur_1.mpg` the main issue is that the file is not detected as a MPEG container (it is detected as raw video), the CLI version prioritizes the MPEG container due to the file extension but not the onlinve version, issue on my side.
For `06.mpg` the difference of behavior may come from how many bytes are provided at each call, I'll try to reproduce the issue, could you log the count of bytes you provide to MediaInfo library at each call + MediaInfoLib seek requests values?

**Comment by buzz** [comment]
> For `06.mpg` the difference of behavior may come from how many bytes are provided at each call, I'll try to reproduce the issue, could you log the count of bytes you provide to MediaInfo library at each call + MediaInfoLib seek requests values?

Chunk size used is `1024*1024` bytes. `Open_Buffer_GoTo` always returns `-1`.

<details>
<summary>Logs</summary>

```
providing data to MediaInfoLib count=1048576 offset=0
MI.Open_Buffer_GoTo()=-1
providing data to MediaInfoLib count=1048576 offset=1048576
MI.Open_Buffer_GoTo()=-1
providing data to MediaInfoLib count=1048576 offset=2097152
MI.Open_Buffer_GoTo()=-1
providing data to MediaInfoLib count=1048576 offset=3145728
MI.Open_Buffer_GoTo()=-1
providing data to MediaInfoLib count=1048576 offset=4194304
MI.Open_Buffer_GoTo()=-1
providing data to MediaInfoLib count=1048576 offset=5242880
MI.Open_Buffer_GoTo()=-1
providing data to MediaInfoLib count=1048576 offset=6291456
MI.Open_Buffer_GoTo()=-1
providing data to MediaInfoLib count=1048576 offset=7340032
MediaInfoLib requested finalizing...
General
Format                                   : MPEG-PS
File size                                : 21.5 MiB
Overall bit rate mode                    : Constant

Video
ID                                       : 224 (0xE0)
Format                                   : MPEG Video
Format version                           : Version 2
Format profile                           : Main@High
Format settings                          : CustomMatrix / BVOP
Format settings, BVOP                    : Yes
Format settings, Matrix                  : Custom
Format settings, GOP                     : M=3, N=15
Bit rate mode                            : Constant
Maximum bit rate                         : 15.0 Mb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate                               : 25.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Compression mode                         : Lossy
Time code of first frame                 : 00:00:47:05
Time code source                         : Group of pictures header

Audio
ID                                       : 192 (0xC0)
Format                                   : MPEG Audio
Format version                           : Version 1
Format profile                           : Layer 2
Bit rate mode                            : Constant
Bit rate                                 : 384 kb/s
Channel(s)                               : 2 channels
Sampling rate                            : 48.0 kHz
Compression mode                         : Lossy
```

</details>

I think the problem may be with `Open_Buffer_Continue`. It is documented [here](https://mediaarea.net/en/MediaInfo/Support/SDK/Buffers). But I never really got to wrap my head around what the return value of this function really means.

**Comment by JeromeMartinez** [comment]
@buzz thanks, I'll check after holidays.
`Open_Buffer_Continue` return value is not so important, but you may stop to parse the file if the return value `&1` (first bit) is 1.

**Comment by buzz** [comment]
It seems to be important as it's the only way to determine if MediaInfoLib is done parsing, isn't it?

I did more testing. If I use the first bit as you suggested, MediaInfoLib will lack fields. Also, sometimes the duration and other fields are either wrong or missing altogether.

In the [MediaInfo JS build](https://github.com/MediaArea/MediaInfoLib/blob/6d94a4306cda5912c9c4b082392cc67c54037955/Source/Resource/JavaScript/Post.js#L37) I can see the fourth bit (bit 3) is tested. If I use this MediaInfoLib is correctly parsing all above test files. Also, then it does have opportunity to seek to the end of the files.

The other factor (called `chunkSize` in mediainfo.js) is also important, as you suggested. The current value of `1024*1024` seems to be too high. With this value all mentioned MPG test files except `centaur_1.mpg` parse correctly. It lacks the usual fields, like duration, stream size, etc. Using a value of `512*1024` works. To be on the safe side I choose `256*1024` for the time being.

I'd greatly appreciate if you could look at this when you find the time.
Thanks.

**Comment by sajadghobadi** [comment]
@buzz  you are the best. it's work great.
thank you very much

**Comment by buzz** [comment]
Closed due to inactivity...
