### ISSUE TITLE
Error when loading mediainfo in frontend

### ISSUE THREAD

**Issue by nelson777** [buzz/mediainfo.js#38]
Hello,

I get this error when trying to load Mediainfo in an Angular 8 project:

ERROR in ./node_modules/mediainfo.js/dist/mediainfo.js
Module not found: Error: Can't resolve 'fs' in '/vagrant/frontend/node_modules/mediainfo.js/dist'
ERROR in ./node_modules/mediainfo.js/dist/mediainfo.js
Module not found: Error: Can't resolve 'path' in '/vagrant/frontend/node_modules/mediainfo.js/dist'

As it's a frontend application I obviously aint got the node's fs module.

I was just trying to run your browser example. Any ideas what may be happening ? 

I have installed it with npm.

**Comment by nelson777** [comment]
Solved it by putting

	"browser": {
		"fs": false,
		"path": false
	},

in package.json

**Comment by C3PablO** [comment]
having the same issue.
I'm running mediainfo.js": "^0.1.4

Also I'm adding this to the webpack.config.js as in the example
```
const wasmFile = path.resolve(
  __dirname,
  'node_modules',
  'mediainfo.js',
  'dist',
  'MediaInfoModule.wasm'
)

...

new CopyPlugin({
    patterns: [
      { from: wasmFile, to: '.' },
    ],
  }),
```

adding what @nelson777 mentioned above to the package.json doesn't help.

anything else I could be missing?

Thanks!

**Comment by tumidi** [comment]
Can you run the [Angular example](https://github.com/buzz/mediainfo.js/tree/master/examples/angular)? It should work.

**Comment by buzz** [comment]
Can you run the [Angular example](https://github.com/buzz/mediainfo.js/tree/master/examples/angular)? It should work.

**Comment by C3PablO** [comment]
I can try. Any relevant difference for working with Webpack/React?

**Comment by tumidi** [comment]
Just check the [React example](https://github.com/buzz/mediainfo.js/tree/gh-pages-src).

**Comment by buzz** [comment]
[React example](https://github.com/buzz/mediainfo.js/tree/gh-pages-src)

**Comment by C3PablO** [comment]
I started with reference but I missed this part:
```
node: {
    fs: 'empty',
  },
```
Also I had to set a different path for the CopyPlugin in my project

Got it working. Thanks a lot

**Comment by buzz** [comment]
> I started with reference but I missed this part:
> 
> ```
> node: {
>     fs: 'empty',
>   },
> ```
> 
> Also I had to set a different path for the CopyPlugin in my project
> 
> Got it working. Thanks a lot

Nice, it worked for you! :+1:

**Comment by khoaanh2212** [comment]
still stuck in this ,
use with Reactjs, any other ideas.thanks

**Comment by buzz** [comment]
> still stuck in this ,
> use with Reactjs, any other ideas.thanks

You can open a [question on SO](http://stackoverflow.com/) and I will try to look into it.

**Comment by moriarais** [comment]
Hi!
I consume the npm package with my Angular 12 project. Even after setting   
```
"browser": {
    "fs": false,
    "path": false
  },
```
in package.json it didn't resolve the issue. I can still see the error:
Error: Module not found: Error: Can't resolve 'fs' in 'C:\.........\mediainfo.js\dist'
Could you please advise in this matter?

**Comment by peter-amd-oona** [comment]
> 

try adding "module": false

or if you have webpack config,
you can put those key-value pairs inside `webpack.configuration.resolve.fallback`
