### ISSUE TITLE
Use with-libcurl

### ISSUE THREAD

**Issue by Headstock67** [buzz/mediainfo.js#43]
This resource has been great! I was able to incorporate mediainfo.js into my project and have been able to extract the metadata I need.

However, whilst testing I have been using the <Input type<file>....... approach for simplicity.

Now I want to ditch that and just directly access the video files on the webserver. The problem is I can't pass a URL to the MediaInfoModule.

Then I read that the CLI version of MediaInfo comes with an option to compile using libcurl. Therefore, allowing a URL to specified. In this instance, it just downloads enough to create the output.

Is there a way of passing a URL?

Thanks

Andrew

**Comment by buzz** [comment]
Downloading files from the web is not the scope of this project.

Are you using the mediainfo.js CLI or as a library from Node.js?

In the first case the are tools like `curl` or `wget` that get the job done. In the latter case please google for `nodejs download file`.

**Comment by Headstock67** [comment]
Thanks for super quick response. I'm not downloading the files from anywhere. They are residing in the same directoy as MediaInfoWasm.js on my web server.

The use case I have is this:

Using ffmpeg, I have set the "Title" metadata field on several webm video files, to a uniqueID.

As mentioned, these files sit on the webserver in the same directory as MediaInfoWasm.js. I now need to extract this "Title" metadata field on these video(s) in question. Then I need to get this uniqueID back into the clientside javascript that is being processed.

I was hoping that MediaInfo.js would just accept the filename. However, it requires a File Object, which can only be created from the Browse buttons HTML <input type="file"> method.

I guess there may be some way of doing this through node.js and MediaInfo CLI compiled --with-libCurl. But I was hoping to avoid that if possible.

Thanks

Andrew

**Comment by buzz** [comment]
mediainfo.js works on buffers, binary data. Not files.

> readChunk(size, offset) - Read data chunk of size with offset and return an Uint8Array.

How you get the data into your specific environment is up to you. Putting libcurl into mediainfo.js would be complete overkill.

**Comment by JeromeMartinez** [comment]
@buzz 

> In the first case the are tools like curl or wget that get the job done. In the latter case please google for nodejs download file.

in such case the file need to be downloaded completely, which is a burden compared to analyze directly by MediaInfo through libcurl.
But building MediaInfo WASM with libcurl would be definitely a pain (even not sure that libcurl could be easily built this way, especially with SSL library for HTTPS), and the preferred way to support that would be to interface the builtin URL support of the language / platform with MediaInfo API.

@Headstock67 

> would just accept the filename. However, it requires a File Object, which can only be created from the Browse buttons HTML method.

You can interface whatever you want, not only the Browse buttons HTML method. You "just" have to interface your preferred method for reading content with MediaInfo (MediaInfo requires only to be able to read data and seek). Just not (yet) done with the file read method you want.

(out or not out of scope is @buzz choice but I understand that they don't want to support more interfaces)

**Comment by buzz** [comment]
> @buzz
> 
> > In the first case the are tools like curl or wget that get the job done. In the latter case please google for nodejs download file.
> 
> in such case the file need to be downloaded completely, which is a burden compared to analyze directly by MediaInfo through libcurl.

I have to disagree on this point. HTTP is actually capable of [partially downloading files](https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests).

**Comment by buzz** [comment]
> I guess there may be some way of doing this through node.js and MediaInfo CLI compiled --with-libCurl. But I was hoping to avoid that if possible.

Compiling with libcurl is not an option as already elaborated on. But adding support for `http/https` in the CLI would be very appreciated. Happy to see a PR on this.
