### ISSUE TITLE
Is it possible to analyze an s3 signed url?

### ISSUE THREAD

**Issue by kotAPI** [buzz/mediainfo.js#48]
Wondering if there are any ways to analyze an s3 asset
What I'm trying to do is store some metadata of the file a user uploads to s3. Is there any way I can pass in a s3 url to the library and analyze it without downloading it?

**Comment by buzz** [comment]
You can analyze arbitrary data. It doesn't matter if it comes from s3 or elsewhere.

Data is analyzed by "streaming" it into the library, [chunk by chunk](https://github.com/buzz/mediainfo.js#mediainfoanalyzedatagetsize-readchunk-cb).

So, there's no need to download the entire file but only the parts that the library requests which normally is only a fraction of the file.

**Comment by kotAPI** [comment]
> You can analyze arbitrary data. It doesn't matter if it comes from s3 or elsewhere.
> 
> Data is analyzed by "streaming" it into the library, [chunk by chunk](https://github.com/buzz/mediainfo.js#mediainfoanalyzedatagetsize-readchunk-cb).
> 
> So, there's no need to download the entire file but only the parts that the library requests which normally is only a fraction of the file.

I see, I thought so looking at the simple browser example. Any tips/examples on how I can pass the URL and make the mediainfo work in this case? Thanks

**Comment by buzz** [comment]
Did you read the README?

https://github.com/buzz/mediainfo.js#examples

**Comment by buzz** [comment]
> Any tips/examples on how I can pass the URL and make the mediainfo work in this case?

You do not pass an URL. You pass binary data.

**Comment by JeromeMartinez** [comment]
> Any tips/examples on how I can pass the URL and make the mediainfo work in this case? 

Just to be avoid misunderstandings: you are in **mediainfo.js** place, not **mediainfo** place. mediainfo.js uses mediainfo library but the way to use is different. Looks like that unlike mediainfo (including JS version) which accepts URL (including S3 URL, presigned or in the form AccessKeyId:SecretAccessKey@URL) but is not so well integrated in JS environment, mediainfo.js expects binary data (your side for getting data).

**Comment by kotAPI** [comment]
Thank you!
