### ISSUE TITLE
Question:  Syntax question

### ISSUE THREAD

**Issue by DongDanBam** [buzz/mediainfo.js#50]
Still trying to figure out how this script operates.  Im trying to hardcode the file that is to be analyzed.

ive replaced `const file = fileinput.files[0]` with `const file = "D:\videoFiles\sampleVideo.mp4`

Then I call the `onChangeFile` class with a button `<button class="btn btn-default" id="getframe" onclick="onChangeFile()">Get Frame Rate</button>`

It never produces a result.  The output displays "Working…"

Is there a different place that I can hardcode the file name & path?

```
 const onChangeFile = (filename) => {
            //const file = fileinput.files[0]
            const file = "D:\videoFiles\sampleVideo.mp4";

            if (file) {

                output.value = 'Working…'
   
                const getSize = () => file.size

                const readChunk = (chunkSize, offset) =>
                    new Promise((resolve, reject) => {
                        const reader = new FileReader()
                        reader.onload = (event) => {
                            if (event.target.error) {
                                reject(event.target.error)
                            }
                            resolve(new Uint8Array(event.target.result))
                        }
                        reader.readAsArrayBuffer(file.slice(offset, offset + chunkSize))
                    })

                mediainfo
                    .analyzeData(getSize, readChunk)
                    .then((result) => {
                        console.log("Frame: " + result.media.track[0].FrameRate);
                        output.value = result;
                    })
                    .catch((error) => {
                        output.value = `An error occured:\n${error.stack}`
                    })
            }
        }
```

**Comment by buzz** [comment]
The repository includes [examples](https://github.com/buzz/mediainfo.js/tree/master/examples) that do work. Just try them. If you need further assistance please check [SO](https://stackoverflow.com/).

Thank you

**Comment by DongDanBam** [comment]
Ive got an example to work just fine. Having trouble understanding how all the hooks and snags work so running a few simple experiments to get acquainted with your creation. Ive been through SO from top to bottom and found only vague references.  I couldn't find any thing on SO that provided enough of a well rounded explanation to help me learn.

How can I hard code a file name and path directly into your code example? seems like I should be able to replace `const file = fileinput.files[0]` with `const file = "D:\videoFiles\sampleVideo.mp4";`
