### ISSUE TITLE
SO Question

### ISSUE THREAD

**Issue by DongDanBam** [buzz/mediainfo.js#54]
Can anyone here answer this question at SO?

https://stackoverflow.com/questions/66243752/mediainfo-js-query-specific-data

**Comment by buzz** [comment]
This issue tracker is mainly for tracking bugs regarding the library. Please refrain from creating multiple redundant issues or advertising your SO question here. Thank you.

**Comment by DongDanBam** [comment]
Common man.  I really need your help.  As far as I know you are the only one that knows how your code works and can help me figure out a couple items (querying frame rate & hard coding a file name).  My pursuit for help at SO isn't getting any hits.  Would you please find kindness and pity and help a poor guy out?
