### ISSUE TITLE
Implemantation with dropzone

### ISSUE THREAD

**Issue by RamosDC** [buzz/mediainfo.js#57]
Hello, I would like to implement mediainfo.js in the following code in dropzone when activating success:

	var varFunc_Dropzone = function () {

		var dzone_upload_show_poster = function () {

			$('#dzone_poster').dropzone({

				url: "../../assets/system/sys_upload_manager.php",
				method: "POST",
				paramName: "file",
				acceptedFiles: "image/*",
				maxFiles: 1,
				maxFilesize: 1, // MB
				uploadMultiple: false,
				// clickable: '#fileinput',
				// createImageThumbnails: true,
				thumbnailWidth: null,
				thumbnailHeight: null,
				addRemoveLinks: true,
				timeout: 180000,
				dictRemoveFileConfirmation: "Sicuro?",
				dictFileTooBig: "File grande ({{filesize}}mb). Massimo consentito {{maxFilesize}}mb",
				dictInvalidFileType: "Tipo di file non valido",
				dictCancelUpload: "Cancella",
				dictRemoveFile: "Rimuovi",
				dictMaxFilesExceeded: "Sono consentiti un massimo di {{maxFiles}} file",
				dictDefaultMessage: "Trascina il file qui per effettuare Upload",

				success: function(file, done) {
// implement the trigger here
				// get_file_info(MediaInfo({ format: 'text' }, {file}));
					// var xFile = MediaInfo({ format: 'text' }, (mediainfo) => {file});
					// fileinput.addEventListener('change', () => onChangeFile(mediainfo));
					// var xFile = MediaInfo({ format: 'text' }, (mediainfo) => onChangeFile(file));

				}

			});

		}

		return {
			init: function() {

				dzone_upload_show_poster();
			}
		};
	}();

	KTUtil.ready(function() { varFunc_Dropzone.init(); });

I try with:
const onChangeFile = (mediainfo) => {
and
function get_file_info(mediainfo, file) {

Thank you for your willingness!!!

**Comment by buzz** [comment]
There's an [example](https://github.com/buzz/mediainfo.js/blob/gh-pages-src/src/components/DropZone.js) of using the library with react-dropzone. I hope it serves your purpose.

For further question regarding the usage of the library I'd like to point you towards [StackOverflow](https://stackoverflow.com/search?q=mediainfo.js) as this issue tracker is primarily for bugs and enhancements.

**Comment by RamosDC** [comment]
Ok sorry! :-( I have post the question here: https://stackoverflow.com/questions/66690951/implemantation-mediainfo-js-with-dropzone-on-success
