### ISSUE TITLE
Scanning through subfolders

### ISSUE THREAD

**Issue by ouafouaf** [buzz/mediainfo.js#64]
Hi, and thanks for your work!  

I would like to be able to fetch metadata from multiple files including subfolders. I tried to modify the multiple-files browser example and use webkitRelativePath, but I didn't manage to make it work. Any chance someone could implement it?

**Comment by buzz** [comment]
The interface to mediainfo.js does not operate on files. You need to pass data using callback functions. Handling multiple files or folders is up to the developer.
