### ISSUE TITLE
TypeError - undefined is not a constructor (evaluating 'new t.MediaInfo(n,l.coverData)')

### ISSUE THREAD

**Issue by bmarotta** [buzz/mediainfo.js#76]
Apparently this error occurs on Apple devices. More details including callstack can be found here:

https://sentry.io/share/issue/bb4ad83167ef482d974e131af45f6a61/

**Comment by buzz** [comment]
Please create a minimal test repo to reproduce.

**Comment by bmarotta** [comment]
@buzz Problem found: it was a mixture of the 0.1.5 js with 0.1.3 wasm file.
