### ISSUE TITLE
Some fields seem to be omitted in subsequential analysis

### ISSUE THREAD

**Issue by NyaomiDEV** [buzz/mediainfo.js#84]
Given this example code:
```ts
import { stat, open } from "fs/promises";
import MediaInfoFactory, { MediaInfo } from "mediainfo.js";
import { ResultObject } from "mediainfo.js/dist/types";

let mediainfoInstance;

async function getMediaInfo(): Promise<MediaInfo> {
	if(!mediainfoInstance){
		mediainfoInstance = await MediaInfoFactory({
			coverData: false,
			format: "object"
		}) as MediaInfo;
	}
	return mediainfoInstance;
}

async function analyze(file){
	const size = (await stat(file)).size;
	const fd = await open(file, "r");
	const readChunk = async (size: number, offset: number) => {
		const buffer = new Uint8Array(size);
		await fd.read(buffer, 0, size, offset);
		return buffer;
	};

	const mediaInfo = await getMediaInfo();

	const rawData = await mediaInfo.analyzeData(() => size, readChunk) as ResultObject;
	fd.close();
	console.log(file, rawData.media.track);
}

analyze("file.mp4");
analyze("file.mts");

getMediaInfo().then(mi => mi.close());
```

and two files with different tags, you will notice that some tags from the second file to analyze are actually missing.
In my test cases, my .mts files were missing the `Recorded_Date` tag.

I cannot provide test files but hopefully it will be easy to reproduce.

**Comment by buzz** [comment]
Not sure how to reproduce this. Please provide a minimal test repository including test files.

**Comment by NyaomiDEV** [comment]
Sorry it's been so long but this issue persists. I know you need a minimal test repository, but I cannot provide one as the test files I have are actually depicting private life.

The minimal test snippet I provided does reproduce this issue still, as long as you have two files of different containers and you are analyzing them using the same MediaInfo instance.

**Comment by buzz** [comment]
This is some sort of edge case I suppose? You could try to recreate the issue using the C library to determine if this is in fact a problem in the emscripten port or MediaInfo itself is affected by this.
Another approach would be to find media files that are shareable that exhibit the same behavior.
Otherwise, I'm afraid, I don't know how to go about this without any means to reproduce.
