### ISSUE TITLE
Not all media info fields reported

### ISSUE THREAD

**Issue by andreash** [buzz/mediainfo.js#93]
When I run an mp4 file against the mediainfo app, I get all fields, specifically including encoding_date - which I am interested in. If I use mediainfo under nodejs (JSON format, coverData=true), the time fields are not included and also no information on the included streams. This is what I get:

`
{
  "creatingLibrary": {
    "name": "MediaInfoLib",
    "version": "21.09",
    "url": "https://mediaarea.net/MediaInfo"
  },
  "media": {
    "@ref": "",
    "track": [
      {
        "@type": "General",
        "Format": "MPEG-4",
        "Format_Profile": "Base Media",
        "CodecID": "mp42",
        "CodecID_Compatible": "isom/mp42",
        "FileSize": "262144",
        "StreamSize": "262144",
        "HeaderSize": "24",
        "DataSize": "262120",
        "FooterSize": "0",
        "IsStreamable": "No",
        "extra": {
          "IsTruncated": "Yes"
        }
      }
    ]
  }
}`

Any ideas? The code is
`
const analyze = async ({ file, format, coverData }) => {
    let fileHandle
    // let fileSize
    let mediainfo

    if (coverData && !['JSON', 'XML'].includes(format)) {
        throw TypeError('For cover data you need to choose JSON or XML as output format!')
    }

    const readChunk = async (size, offset) => {
        const buffer = new Uint8Array(size)
        await fileHandle.read(buffer, 0, size, offset)
        return buffer
    }

    let result;
    try {
        fileHandle = await fsPromises.open(file, 'r')
        // let stat = (await fileHandle.stat());
        // fileSize = stat.size;

        let chunkSize = 256 * 1024;
        mediainfo = (await MediaInfoFactory({ format, coverData }));
        result = await mediainfo.analyzeData(() => chunkSize, readChunk);
    } catch (err) {
        throw err
    } finally {
        fileHandle && (await fileHandle.close())
        mediainfo && mediainfo.close()
        return result;
    }
}
`

**Comment by buzz** [comment]
I can't reproduce this. Tried your code example as well as the mediainfo.js CLI.
Has this to do with a specific MP4 you're trying to analyze? Did you try other MP4 files?

**Comment by JeromeMartinez** [comment]
`"StreamSize": "262144"` and `"IsTruncated": "Yes"`, the file header can not be read because there is only 256 KiB provided to the parser and most of that is the data part. The file track header is at the end of the file and not provided.

**Comment by andreash** [comment]
Thanks, that sounds like some helpful idea. So do I need to provide the whole file size and does mediainfo need to digest the whole video file? A thought it would digest it chunk by chunk, reading all necessary chunks and not the whole file?

**Comment by JeromeMartinez** [comment]
The MediaInfo library (used by mediainfo.js) does not need the whole file, and says when it needs to seek when data is provided by external methods (like what is done in mediainfo.js IIUC).
I can not speak about mediainfo.js interface as I don't know it, but the MediaInfo library has an init part for providing size (can be set to "unknown" but in that case some formats are not totally well supported) and a seek request interface which permit the calling program to know if it needs to seek.
[example](https://github.com/MediaArea/MediaInfoLib/blob/master/Source/Example/HowToUse_Dll.html#L84-L130) (for MediaInfo library, in JS but not mediainfo.js, you need to adapt to mediainfo.js).

**Comment by celesta-origin** [comment]
DeprecationWarning: Invalid 'main' field in '/app/node_modules/simple-exiftool/package.json' of './lib/exif'.
