### ISSUE TITLE
Unsafe eval error

### ISSUE THREAD

**Issue by moriarais** [buzz/mediainfo.js#96]
Getting the following error after using mediaInfo package:
EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' blob:....
Any suggestion how to resolve it?

**Comment by buzz** [comment]
emscripten might use some `eval` somewhere in its glue code.

Other than that, it's hard to give suggestions without specific information from your side.

**Comment by moriarais** [comment]
Thanks for replying. I am using the package exactly as the doc recommend. When checking my app with prod env and on chrome browser I getting this error. Earlier I didn't have any issue. Our app is Angular 13 based.
What kind of information do you need? 
This is more info about the error I am getting:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#unsafe_eval_expressions
Most of the changes it connected to the mediaInfo package.

**Comment by buzz** [comment]
> and the second one seems to be very complicated since it requires to download the wasm file into our own repo. Is that right.

You'd need to configure emscripten accordingly and build the project yourself.

> Can you please think of another solution that might feet here?

Without any specific information from your side can only give general guidance.

**Comment by moriarais** [comment]
@buzz any answer?

**Comment by buzz** [comment]
> @buzz any answer?

[Look here](https://github.com/buzz/mediainfo.js/issues/96#issuecomment-1041556631)

**Comment by moriarais** [comment]
Already saw. And the solution aren't relevant for us. Do you have other suggestions? or else we consider to use another library.
BTW Security issue is basic requirement so you might consider to change it from the code itself

**Comment by buzz** [comment]
> And the solution aren't relevant for us.

I disagree. The solution given addresses the specific issue you have:

```
// When set to 0, we do not emit eval() and new Function(), which disables some functionality
// (causing runtime errors if attempted to be used), but allows the emitted code to be
// acceptable in places that disallow dynamic code execution
```
Source: https://github.com/emscripten-core/emscripten/blob/513bcf47ff9bbd71896d1d80fd0310a9ee7e4cd5/src/settings.js#L1212

If you disagree how this situation is handled in emscripten, feel free to head over to the emscripten project. This is not the place.

If you want to create variant of mediainfo.js without `DYNAMIC_EXECUTION` feel free to contribute by submitting a PR for review.

Closing this issue as the conversation goes round in circles.
